# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: [pyproject-flake8]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
      - id: mypy
        additional_dependencies:
          - pydantic
          - types-requests

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/magenta-aps/pre-commit-hooks
    rev: c0e34679c2a350832a2370ddb2403348d93067cb
    hooks:
      - id: auto-ticket-prepare-commit
      - id: auto-ticket-commit

  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.1.2
    hooks:
      - id: reuse

  - repo: https://github.com/fpgmaas/deptry.git
    rev: 0.16.1
    hooks:
      - id: deptry
