# SPDX-FileCopyrightText: 2019-2020 Magenta ApS
# SPDX-License-Identifier: MPL-2.0
services:
  os2sync_export:
    build:
      context: .
    env_file:
      - docker.env
    command: ["uvicorn", "--factory", "os2sync_export.main:create_app", "--host", "0.0.0.0", "--reload"]
    ports:
      - 127.0.0.1:8000:8000/tcp
    volumes:
      - ./os2sync_export:/app/os2sync_export
    networks:
      - os2mo_default
  mo-init:
    image: magentaaps/os2mo-init:5
    environment:
      MO_URL: "http://mo:5000"
      CLIENT_ID: "dipex"
      CLIENT_SECRET: "603f1c82-d012-4d04-9382-dbe659c533fb"
      AUTH_SERVER: "http://keycloak:8080/auth"
      AUTH_REALM: "mo"
    volumes:
      - type: bind
        source: ./init.config.yml
        target: /config/config.yml
        read_only: true
    restart: on-failure
    networks:
      - os2mo_default

networks:
  os2mo_default:
    external: true
